# Generated by Django 6.1.1 on 2026-10-04 14:11

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(default='planned', max_length=10)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('code', models.CharField(default=core.models.new_code, max_length=8, unique=True)),
            ],
            options={
                'ordering': ['scheduled_for', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Ce que fait le produit')),
                ('audience', models.CharField(max_length=200, verbose_name='Cible')),
                ('offer', models.CharField(blank=True, max_length=200, verbose_name='Offre / promesse')),
                ('tone', models.CharField(default='chaleureux et direct', max_length=80, verbose_name='Ton')),
                ('url', models.URLField(verbose_name='Lien de destination (site, WhatsApp, Telegram…)')),
                ('channels', models.CharField(default='whatsapp,facebook,tiktok,telegram', max_length=120, verbose_name='Canaux (séparés par des virgules)')),
                ('token', models.CharField(default=core.models.new_token, editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='signup', max_length=40)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
