# Generated by Django 6.1.1 on 2026-10-04 23:21

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#2b3fa0', max_length=7, verbose_name='Couleur de marque'),
        ),
        migrations.AddField(
            model_name='project',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp (avec indicatif, ex. 22370000000)'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=90)),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Mots-clés (séparés par des virgules)')),
                ('body', models.TextField(verbose_name='Texte (une ligne vide entre les paragraphes)')),
                ('published', models.BooleanField(default=False, verbose_name='Publié sur le blog')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='nouveau', max_length=10)),
                ('code', models.CharField(default=core.models.new_code, max_length=8, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.lead')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code promo')),
                ('label', models.CharField(max_length=120, verbose_name='Offre (ex. -10 % sur la 1re commande)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
