# Generated by Django 6.1.1 on 2026-10-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_color_project_whatsapp_article_lead_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='blog_per_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Désactivé'), (1, '1 article par semaine'), (2, '2 par semaine'), (3, '3 par semaine'), (5, '5 par semaine'), (7, '1 article par jour')], default=0, verbose_name='Rythme du blog automatique'),
        ),
        migrations.AddField(
            model_name='project',
            name='blog_topics',
            field=models.TextField(blank=True, verbose_name='Sujets à traiter (un par ligne)'),
        ),
    ]
