# Generated by Django 6.1.1 on 2026-10-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_publish_at_article_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='event_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='conversion',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='monthly_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Coût mensuel de ta communication en FCFA (publicité, data, temps payé)'),
        ),
        migrations.AddConstraint(
            model_name='conversion',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('project', 'event_id'), name='uniq_event'),
        ),
    ]
